---
name: Nix

on: push

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        devShell:
          - ghc810
          - ghc90
        exclude:
          - os: macos-latest
            devShell: ghc90

      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          # https://input-output-hk.github.io/haskell.nix/tutorials/getting-started.html
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org
      # https://github.com/actions/cache/blob/main/examples.md#haskell---cabal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ matrix.os }}-${{ matrix.devShell }}-${{ hashFiles('*.cabal') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.devShell }}-
      - name: Install packages via Nix
        run: ./bin/${{ matrix.devShell }} -c ghc --version
      - name: Update package index
        run: ./bin/${{ matrix.devShell }} -c cabal update
      - name: Enable tests
        run: ./bin/${{ matrix.devShell }} -c cabal configure --enable-tests
      - name: Install project dependencies
        run: ./bin/${{ matrix.devShell }} -c cabal build --only-dependencies
      - name: Compile project
        run: ./bin/${{ matrix.devShell }} -c cabal build
      - name: Run tests
        run: ./bin/${{ matrix.devShell }} -c cabal test
