---
name: Nix

on: push

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
        devShell:
          - ghc8107
          # - ghc90
        # exclude:
        #   - os: macos-latest
        #     devShell: ghc810

      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io
      # https://github.com/actions/cache/blob/main/examples.md#haskell---cabal
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ matrix.os }}-${{ matrix.devShell }}-${{ hashFiles('*.cabal') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.devShell }}-
      # https://serokell.io/blog/practical-nix-flakes
      - run: nix develop github:input-output-hk/haskell.nix#${{ matrix.devShell }} --accept-flake-config -c cabal update
      - run: nix develop github:input-output-hk/haskell.nix#${{ matrix.devShell }} --accept-flake-config -c cabal configure --enable-tests
      - run: nix develop github:input-output-hk/haskell.nix#${{ matrix.devShell }} --accept-flake-config -c cabal build
      - run: nix develop github:input-output-hk/haskell.nix#${{ matrix.devShell }} --accept-flake-config -c cabal test
