---
name: Nix

on: push

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
        devShell:
          - ghc810
          # - ghc90

      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          # https://input-output-hk.github.io/haskell.nix/tutorials/getting-started.html
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org
      # https://github.com/actions/cache/blob/main/examples.md#haskell---cabal
      - run: nix-shell -p nix-info --run "nix-info -m"
      - run: ls -al /usr/lib/x86_64-linux-gnu/ | grep libstd
      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cabal/packages
      #       ~/.cabal/store
      #       dist-newstyle
      #     key: ${{ matrix.os }}-${{ matrix.devShell }}-${{ hashFiles('*.cabal') }}
      #     restore-keys: ${{ matrix.os }}-${{ matrix.devShell }}-
      # - run: nix develop .#${{ matrix.devShell }} --accept-flake-config -c ghc --version
      # - run: nix develop .#${{ matrix.devShell }} -c cabal update
      # - run: nix develop .#${{ matrix.devShell }} -c cabal configure --enable-tests
      # - run: nix develop .#${{ matrix.devShell }} -c cabal build --only-dependencies
      # - run: nix develop .#${{ matrix.devShell }} -c cabal build
      # - run: nix develop .#${{ matrix.devShell }} --accept-flake-config -c cabal test
